function Get-TfsTeamProjectDashboard
{
    <#  
        .SYNOPSIS
            This function will return all dashboards associated with a specific team project.

        .DESCRIPTION
            This function will return all dashboards associated with a specific team project.

            The function will take either a websession object or a uri and
            credentials. The web session can be piped to the fuction from the
            Connect-TfsServer function.

        .PARAMETER WebSession
            Websession with connection details and credentials generated by Connect-TfsServer function

        .PARAMETER Team
            The name of the team who's dashboards should be returned

        .PARAMETER Project
            The name of the project containing the dashboard

        .PARAMETER Uri
            Uri of TFS serverm, including /DefaultCollection (or equivilent)

        .PARAMETER Username
            The username to connect to the remote server with

        .PARAMETER AccessToken
            Access token for the username connecting to the remote server

        .PARAMETER UseDefaultCredentails
            Switch to use the logged in users credentials for authenticating with TFS.

        .EXAMPLE
            Get-TfsTeamProjectDashboard -WebSession $Session -Team 'Engineering' -Project 'Super Product'

            This will return any dashboards that are on the Super Product project and linked to the Engineering team 
            using the already established session.

        .EXAMPLE
            Get-TfsTeamProjectDashboard -Uri 'https://test.visualstudio.com/defaultcollection'  -Username username@email.com -AccessToken (Get-Content C:\AccessToken.txt) -Team 'Engineering' -Project 'Super Product'

            This will return any dashboards that are on the Super Product project and linked to the Engineering team 
            using the provided credentials and uri.

    #>
    [cmdletbinding()]
    param
    (
        [Parameter(ParameterSetName='WebSession', Mandatory,ValueFromPipeline)]
        [Microsoft.PowerShell.Commands.WebRequestSession]$WebSession,

        [Parameter(Mandatory)]
        [String]$Team,

        [Parameter(Mandatory)]
        [String]$Project,

        [Parameter(ParameterSetName='SingleConnection',Mandatory)]
        [Parameter(ParameterSetName='LocalConnection',Mandatory)]
        [String]$uri,

        [Parameter(ParameterSetName='SingleConnection',Mandatory)]
        [string]$Username,

        [Parameter(ParameterSetName='SingleConnection',Mandatory)]
        [string]$AccessToken,

        [parameter(ParameterSetName='LocalConnection',Mandatory)]
        [switch]$UseDefaultCredentials

    )
    Process
    {
        $headers = @{'Content-Type'='application/json-patch+json'}
        $Parameters = @{}

        #Use Hashtable to create param block for invoke-restmethod and splat it together
        switch ($PsCmdlet.ParameterSetName) 
        {
            'SingleConnection'
            {
                $WebSession = Connect-TfsServer -Uri $uri -Username $Username -AccessToken $AccessToken
                $Parameters.add('WebSession',$WebSession)
                $Parameters.add('Headers',$headers)

            }
            'LocalConnection'
            {
                $WebSession = Connect-TfsServer -uri $Uri -UseDefaultCredentials
                $Parameters.add('WebSession',$WebSession)
                $Parameters.add('Headers',$headers)
            }
            'WebSession'
            {
                $Uri = $WebSession.uri
                $Parameters.add('WebSession',$WebSession)
                $Parameters.add('Headers',$headers)
                #Connection details here from websession, no creds needed as already there
            }
        }

        #Construct the uri and add it to paramaters block
        $TeamId = Get-TfsTeam -WebSession $Websession -Project $Project | Where-Object Name -eq "$Team" | Select-Object -ExpandProperty id
        $uri = "$uri/$($Project)/_apis/Dashboard/Groups/$($TeamId)"
        $Parameters.add('Uri',$uri)


        try
        {
            $jsondata = Invoke-restmethod @Parameters -erroraction Stop
        }
        catch
        {
            throw
        }

        Write-Output $jsondata.dashboardentries

    }
}
